# Generated by Django 3.2.6 on 2021-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, verbose_name='День рождение'),
        ),
    ]
